### ISSUE TITLE
About the current managed runtime seems to have crashed.

### ISSUE THREAD

**Issue by ShangweiGuo** [eleboss/fast_EDI#3]
After following the instructions to complete the setup (the version of dv-gui and dv-runtime provided by the official website is 1.6.2) and compiling successfully, once the fast-gui module is added, the module does not show the memory footprint when running at DV-gui, it shows that the current managed runtime seems to have crashed.

**Comment by eleboss** [comment]
No idea why, have you tested the 1.6?

**Comment by harpun11** [comment]
I have exactly the same problem. I have tried downgrading to 1.6 but the problem still remains. Do you have a version of the algorithm that does not use the GUI mentioned?

**Comment by eleboss** [comment]
upgraded cmake file for 1.6.2
